# CI de nível 01 - Disparo através de clique

#nome da pipeline
name: 'Execução Manual com Self-Hosted'

#gatilhos/triggers - regras de disparo
#gatilho manual = workflow dispatch

on:
  workflow_dispatch: 


#definicao de tarefas dentro da pipeline
jobs: 
  #nome do job
  e2e-tests: 
      #Para rodar self-hosted basta trocar o runs-on para self-hosted:
      runs-on: self-hosted

      defaults:
        run:
          shell: cmd

      #passos do job
      steps:
          # clone do projeto
          - uses: actions/checkout@v4          

          # execucao dos testes
          - name: execucao dos testes
            run:  yarn run e2e


                        
              
